# Generated by Django 3.1.5 on 2021-01-10 11:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 10, 11, 36, 52, 91373, tzinfo=utc)),
        ),
    ]
